### ISSUE TITLE
Generalising code between Pool and Transaction

### ISSUE THREAD

**Issue by dave42w** [digital-society-coop/axum-sqlx-tx#30]
Hi,

This looks great and solves a key problem for me.

I have various models and some handlers need to call functions on multiple models. I have been wondering how to make this work for transactions. At the moment I can switch everything to use Transactions instead of the Pool.

However, I wonder if there is a way to write functions so that they use Executors rather then Pools or Transactions. Then they can work with either depending on the calling method.

Mind you at the same time it would be wonderful if we could move towards a point where we use the generic Executor rather than the db specific ones so that it would be easier to provide both sqlite and postgres support. I'm not sure that sqlx is ready for that though.

**Comment by connec** [comment]
It is possible to write a function that is generic for any [`sqlx::Executor`](https://docs.rs/sqlx/latest/sqlx/trait.Executor.html) and [`sqlx::Database`](https://docs.rs/sqlx/latest/sqlx/trait.Database.html), e.g.

```rust
// "model" function
async fn save<'c, E>(executor: E)
where
    E: sqlx::Executor<'c>,
{
    executor.execute("INSERT INTO ...").await.unwrap();
}

async fn save_with_pool<DB>(pool: sqlx::Pool<DB>)
where
    DB: sqlx::Database,
    for<'c> &'c mut DB::Connection: sqlx::Executor<'c, Database = DB>,
{
    // `save` can be called with a pool
    save(&pool).await;
}

async fn save_with_tx<DB>(mut tx: axum_sqlx_tx::Tx<DB>)
where
    DB: sqlx::Database,
    for<'c> &'c mut DB::Connection: sqlx::Executor<'c, Database = DB>,
{
    // `save` can be called with a transaction
    save(&mut tx).await;
}
```

Being generic on `DB` requires most of the bounds, and when the `DB` generic is known it gets a lot simpler (using sqlite as an example):

```rust
async fn save<'c, E>(executor: E)
where
    E: sqlx::Executor<'c>,
{
    executor.execute("INSERT INTO ...").await.unwrap();
}

async fn save_with_pool(pool: sqlx::Pool<sqlx::Sqlite>) {
    save(&pool).await;
}

async fn save_with_tx(mut tx: axum_sqlx_tx::Tx<sqlx::Sqlite>) {
    save(&mut tx).await;
}
```

Is this the kind of thing you're trying to do?

**Comment by dave42w** [comment]
Hi,
Thanks. This is exactly the sort of thing I was looking for. 

If I understand correctly then Marker https://docs.rs/axum-sqlx-tx/latest/axum_sqlx_tx/trait.Marker.html is a way to allow me to pass a transaction to a handler that is not type specific to a particular database driver.

So if I combine using Marker to pass generic transactions to my models I could create a Trait Model that would give implementations for save_with_tx and and save_with_pool so each Model would only need to implement save?

I'm still a rust noob. So this has been very helpful.

Thanks

**Comment by connec** [comment]
I think what you're describing should work – though it can get pretty hairy combining generics with traits and async. Good luck!
